# Cloud Run Service Configuration
# Use this for manual deployments or as reference

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: your-service-name
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/cpu-throttling: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "1Gi"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: redstring-service-account@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/redstring-app:latest
        ports:
        - containerPort: 4000
          name: http1
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: OAUTH_PORT
          value: "3002"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: github-client-secret
        - name: VITE_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: github-client-id
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true