version: '3.8'

services:
  redstring:
    build: .
    ports:
      - "4000:4000"  # Main app
      - "3002:3002"  # OAuth server
    environment:
      - NODE_ENV=production
      - PORT=4000
      - OAUTH_PORT=3002
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Optional: Redis for client storage in production
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped